<?php include 'inc/header.phtml'; ?>
<?php if (isset($error)): ?>
            <h3 class="error">You must enter values in the textarea.</h3>
<?php endif; ?>
            <p class="center">
                Examples values: 320, 4.7k, 27k, 470k, &amp; 1.1M<br /><br />
                You can also specify the tolerance, power and composition like this:<br />
                27K,5%,0.5W,CC or 100K,1%,3W,MO<br /><br />
                <em>(CF = Carbon Film, MF = Metal Film, CC = Carbon Comp, MO = Metal Oxide, CE = Ceramic Comp)</em>
            </p>
            <form id="resistor-form" action="/" method="post" enctype="multipart/form-data">
                <div>
                    <label for="text_values">Enter the resistor values, one per line:</label>
                    <textarea class="form-control" name="text_values" id="text_values" cols="80" rows="10"></textarea>
                </div>
                <div>
                    <label for="format">Format:</label>
                    <select id="format" name="format" class="inline-block">
                        <option value="pdf">PDF</option>
                        <option value="jpg-300">JPG (300 dpi)</option>
                        <option value="jpg-72">JPG (72 dpi)</option>
                    </select>
                    <select id="suffix" name="suffix" class="inline-block">
                        <option value="none">[Suffix]</option>
                        <option value="r-1000">"R" on < 1k</option>
                        <option value="r-all">"R" on all</option>
                    </select>
                    <fieldset>
                        <input type="checkbox" name="allow_three_band" id="allow_three_band" value="0" /> Allow 3-band?
                    </fieldset>
                </div>
                <div>
                    <button type="submit" class="btn btn-md btn-info btn-block text-uppercase">Submit</button>
                </div>
            </form>
<br /><br />
            <table class="table table-borderless color-guide-table">
                <thead>
                    <tr>
                        <th>Color</th>
                        <th>1st Digit</th>
                        <th>2nd Digit</th>
                        <th>3rd Digit</th>
                        <th>Multiplier</th>
                        <th>Tolerance</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="code-black">Black</td>
                        <td class="code-black">0</td>
                        <td class="code-black">0</td>
                        <td class="code-black">0</td>
                        <td class="code-black">x1</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="code-brown">Brown</td>
                        <td class="code-brown">1</td>
                        <td class="code-brown">1</td>
                        <td class="code-brown">1</td>
                        <td class="code-brown">x10</td>
                        <td class="code-brown">1%</td>
                    </tr>
                    <tr>
                        <td class="code-red">Red</td>
                        <td class="code-red">2</td>
                        <td class="code-red">2</td>
                        <td class="code-red">2</td>
                        <td class="code-red">x100</td>
                        <td class="code-red">2%</td>
                    </tr>
                    <tr>
                        <td class="code-orange">Orange</td>
                        <td class="code-orange">3</td>
                        <td class="code-orange">3</td>
                        <td class="code-orange">3</td>
                        <td class="code-orange">x1000</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="code-yellow">Yellow</td>
                        <td class="code-yellow">4</td>
                        <td class="code-yellow">4</td>
                        <td class="code-yellow">4</td>
                        <td class="code-yellow">x10000</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="code-green">Green</td>
                        <td class="code-green">5</td>
                        <td class="code-green">5</td>
                        <td class="code-green">5</td>
                        <td class="code-green">x100000</td>
                        <td class="code-green">0.5%</td>
                    </tr>
                    <tr>
                        <td class="code-blue">Blue</td>
                        <td class="code-blue">6</td>
                        <td class="code-blue">6</td>
                        <td class="code-blue">6</td>
                        <td class="code-blue">x1000000</td>
                        <td class="code-blue">0.25%</td>
                    </tr>
                    <tr>
                        <td class="code-violet">Violet</td>
                        <td class="code-violet">7</td>
                        <td class="code-violet">7</td>
                        <td class="code-violet">7</td>
                        <td class="code-violet">x10000000</td>
                        <td class="code-violet">0.1%</td>
                    </tr>
                    <tr>
                        <td class="code-gray">Gray</td>
                        <td class="code-gray">8</td>
                        <td class="code-gray">8</td>
                        <td class="code-gray">8</td>
                        <td class="code-gray">x100000000</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="code-white">White</td>
                        <td class="code-white">9</td>
                        <td class="code-white">9</td>
                        <td class="code-white">9</td>
                        <td class="code-white">x1000000000</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="code-gold">Gold</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td class="code-gold">x0.1</td>
                        <td class="code-gold">5%</td>
                    </tr>
                    <tr>
                        <td class="code-silver">Silver</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td class="code-silver">x0.01</td>
                        <td class="code-silver">10%</td>
                    </tr>
                </tbody>
            </table>
<?php include 'inc/footer.phtml'; ?>
