        <div class="footer center">
            Version <?=$version; ?><br />
            Copyright &copy; <?=date('Y'); ?>. All Rights Reserved.<br />
            SonicTone Amplification, LLC<br />
            <a href="https://www.sonictoneamps.com/" target="_blank">www.sonictoneamps.com</a><br />
            <a href="https://github.com/nicksagona/resistor-color-codes" target="_blank"><i class="fa fab fa-github"></i> GitHub</a><br /><br />
            If you have any issues or questions about this resource,<br />please contact <a href="" class="contact-email" target="_blank"></a>
        </div>
    </div>
    <script src="/assets/js/jquery-3.5.1.min.js"></script>
    <script src="/assets/js/popper.min.js"></script>
    <script src="/assets/js/bootstrap.min.js"></script>
    <script src="/assets/js/font-awesome-5.15/all.min.js"></script>
    <script src="/assets/js/app.min.js"></script>
</body>

</html>