<!DOCTYPE html>
<!-- Header //-->
<html>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Resistor Color Code Label Maker</title>

    <link rel="stylesheet" type="text/css" href="/assets/app.css" />

</head>

<body>
    <div class="container-fluid">
        <div class="col-md-12">
            <img class="logo" src="/assets/img/resistance.png" />
            <h3>Resistor Color Code</h3>
            <h1>Label Maker</h1>
