<!DOCTYPE html>
<!-- Header //-->
<html>

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="resistor colors, resistor color bands, resistor color codes, resistor color label maker" />
    <meta name="description" content="This website is a quick tool to help you make resistor color code labels." />
    <meta name="author" content="Nick Sagona" />
    <meta name="robots" content="all" />

    <title>Resistor Color Code Label Maker</title>

    <link type="image/png" rel="shortcut icon" href="/assets/img/sonictone-icon1-16x16.png"  />
    <link rel="stylesheet" type="text/css" href="/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/assets/css/font-awesome-5.15/all.min.css" />
    <link rel="stylesheet" type="text/css" href="/assets/css/app.min.css" />

</head>

<body>
    <div class="container">
            <img src="/assets/img/sonictone-logo-white.jpg" />
            <h2 class="main-header">Resistor Color Codes</h2>

